/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    ChallengeCard: typeof import('./components/challenge/ChallengeCard.vue')['default']
    EventCard: typeof import('./components/event/EventCard.vue')['default']
    EventForm: typeof import('./components/event/EventForm.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    PhotoCapture: typeof import('./components/shared/PhotoCapture.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UnderConstruction: typeof import('./components/UnderConstruction.vue')['default']
  }
}
