/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/events/[id]': RouteRecordInfo<'/dashboard/events/[id]', '/dashboard/events/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dashboard/events/create': RouteRecordInfo<'/dashboard/events/create', '/dashboard/events/create', Record<never, never>, Record<never, never>>,
    '/event/': RouteRecordInfo<'/event/', '/event', Record<never, never>, Record<never, never>>,
    '/event/challenges': RouteRecordInfo<'/event/challenges', '/event/challenges', Record<never, never>, Record<never, never>>,
    '/event/gallery': RouteRecordInfo<'/event/gallery', '/event/gallery', Record<never, never>, Record<never, never>>,
    '/event/join': RouteRecordInfo<'/event/join', '/event/join', Record<never, never>, Record<never, never>>,
    '/event/leaderboard': RouteRecordInfo<'/event/leaderboard', '/event/leaderboard', Record<never, never>, Record<never, never>>,
    '/legalNotice': RouteRecordInfo<'/legalNotice', '/legalNotice', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/privacyPolicy': RouteRecordInfo<'/privacyPolicy', '/privacyPolicy', Record<never, never>, Record<never, never>>,
  }
}
