# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Hive Pics Frontend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'hive-pics-frontend/**'
      - '.github/workflows/hive-pics-frontend.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'hive-pics-frontend/**'
      - '.github/workflows/hive-pics-frontend.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    defaults:
      run:
        working-directory: hive-pics-frontend

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
        node-version: ${{ matrix.node-version }}
        cache-dependency-path: hive-pics-frontend/package-lock.json
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test:unit -- --run

      # Upload the build artifacts for the docker job
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: hive-pics-frontend/dist

  docker:
    needs: build  # This ensures docker job runs only after successful build
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: 'id_token'
          workload_identity_provider: 'projects/397434637430/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-publisher@hive-pics.iam.gserviceaccount.com'

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker europe-docker.pkg.dev --quiet
      
      # Download the build artifacts
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: hive-pics-frontend/dist
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: hive-pics-frontend
          push: false  # Set to true if you want to push to a registry
          tags: hive-pics-frontend:latest
